application: pittgot
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: code.app

- url: /static/js
  static_dir:  static/js